spring.datasource.url=jdbc:postgresql://ep-proud-hall-alzvlm7t-pooler.c-3.eu-central-1.aws.neon.tech/task_manager?sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=neondb_owner
spring.datasource.password=npg_uTrJo1Kzjv0c

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect